name: StoryTime CI Workflow

run-name: ${{ github.actor }} pushed new update

on: push

jobs:
  build:
    runs-on: ${{ matrix.List_os }}
    strategy:
      matrix:
        List_os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
        - uses: actions/checkout@v3
        - run: cd Source
        - name: run makefile for testing
          run: make TARGET=test
