name: StoryTime CI Workflow

run-name: ${{ github.actor }} pushed new update

on: 
  push:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.List_os }}
    strategy:
      matrix:
        List_os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: run makefile for testing
          working-directory: ./Source
          run: make TARGET=test
